# Generated by Django 4.1.4 on 2022-12-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subquestion',
            options={'verbose_name': 'Подвопрос', 'verbose_name_plural': 'Подвопросы'},
        ),
        migrations.AddField(
            model_name='question',
            name='is_radio',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
