# Generated by Django 4.1.4 on 2022-12-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_is_select_alter_question_is_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='is_radio_activate',
            field=models.BooleanField(default=False, verbose_name='Статус активатора radio'),
        ),
    ]
