# Generated by Django 4.1.4 on 2022-12-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_question_is_radio_activate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='answer',
            field=models.CharField(max_length=256, null=True, verbose_name='Ответ'),
        ),
    ]
