# Generated by Django 4.1.4 on 2022-12-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_subquestion_answer_alter_subquestion_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('changed_name', models.BooleanField(blank=True, default=False, verbose_name='Смена имени')),
                ('changed_firstname', models.CharField(max_length=50, verbose_name='Прошлое имя')),
                ('changed_lastname', models.CharField(max_length=50, verbose_name='Прошлое имя')),
                ('passport_no', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('nation', models.CharField(max_length=50, verbose_name='Нация')),
                ('religion', models.CharField(max_length=50, verbose_name='Религия')),
                ('is_tattoo', models.BooleanField(default=False, verbose_name='Татуировка или родимые пятна')),
                ('education', models.CharField(max_length=50, verbose_name='Оброзование')),
                ('citizenship', models.CharField(max_length=50, verbose_name='Гражданство')),
                ('present_address', models.CharField(max_length=256, verbose_name='Действующий адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('father_data', models.CharField(max_length=50, verbose_name='Данные отца ')),
                ('mother_data', models.CharField(max_length=50, verbose_name='Данные матери ')),
                ('martial_status', models.CharField(max_length=50, verbose_name='Семейный статус ')),
                ('spouse_name', models.CharField(blank=True, max_length=50, verbose_name='Имя супруга ')),
                ('spouse_nation', models.CharField(blank=True, max_length=50, verbose_name='Нация супруга ')),
                ('spouse_country', models.CharField(blank=True, max_length=50, verbose_name='Страна рождения супруга ')),
                ('spouse_city', models.CharField(blank=True, max_length=50, verbose_name='Город рождения супруга ')),
                ('occupation', models.CharField(max_length=50, verbose_name='Профессия ')),
                ('company_name', models.CharField(blank=True, max_length=70, verbose_name='Название компании ')),
                ('company_position', models.CharField(blank=True, max_length=70, verbose_name='Должность ')),
                ('company_addess', models.CharField(blank=True, max_length=100, verbose_name='Адрес ')),
                ('company_number', models.CharField(blank=True, max_length=100, verbose_name='Номер компании ')),
                ('is_served', models.BooleanField(default=False, verbose_name='Служил в армии')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Бронирование отели')),
                ('tour_name', models.CharField(blank=True, max_length=100, verbose_name='Название тур оператора ')),
                ('tour_address', models.CharField(blank=True, max_length=100, verbose_name='Адрес тур оператора ')),
                ('hotel_name', models.CharField(blank=True, max_length=100, verbose_name='Название гостиницы ')),
                ('hotel_location', models.CharField(blank=True, max_length=100, verbose_name='Расположение гостиницы ')),
                ('is_visited', models.BooleanField(default=False, verbose_name='Визит в индию(было/не было)')),
                ('is_visited_address', models.BooleanField(blank=True, default=False, verbose_name='Адрес проживали')),
                ('is_visited_cities', models.CharField(blank=True, max_length=256, verbose_name='Посещенные городы ')),
                ('is_visited_visa_no', models.CharField(blank=True, max_length=100, verbose_name='Номер последней визы ')),
                ('is_visited_visa_type', models.CharField(blank=True, max_length=100, verbose_name='Место выдачи визы ')),
                ('is_visited_visa_date', models.DateField(blank=True, verbose_name='Дата визы ')),
                ('is_refused', models.BooleanField(default=False, verbose_name='Отказ на въезд(было/не было)')),
                ('is_refused_no', models.CharField(blank=True, max_length=100, verbose_name='Контрольный номер ')),
                ('is_refused_date', models.CharField(blank=True, max_length=100, verbose_name='Дата отказа ')),
                ('visited_countries', models.TextField(verbose_name='Визиты за последние 10 лет ')),
                ('visited_countries_sarca', models.TextField(verbose_name='Визиты в SARCA ')),
                ('is_deported', models.BooleanField(default=False, verbose_name='Депорт(было/не было)')),
                ('is_criminal', models.BooleanField(default=False, verbose_name='Судимость(было/не было)')),
            ],
        ),
    ]
