# Generated by Django 3.2.9 on 2022-12-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_questionnaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Фото:'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='passport_image',
            field=models.ImageField(null=True, upload_to='passport_images', verbose_name='Фото паспорта:'),
        ),
    ]
