# Generated by Django 3.2.9 on 2022-12-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20221219_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='question',
            name='placeholder',
            field=models.CharField(max_length=256, null=True, verbose_name='placeholder'),
        ),
    ]
