# Generated by Django 3.2.9 on 2022-12-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20221219_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_radio',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус radio'),
        ),
    ]
