# Generated by Django 3.2.9 on 2022-12-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_question_is_radio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_radio',
            field=models.BooleanField(default=False, verbose_name='Статус radio'),
        ),
        migrations.AlterField(
            model_name='question',
            name='placeholder',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='placeholder'),
        ),
    ]
