# Generated by Django 3.2.9 on 2022-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20221219_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='placeholder',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='placeholder'),
        ),
    ]
