# Generated by Django 3.2.9 on 2022-12-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_question_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='company_addess',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='martial_status',
            new_name='marital_status',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='visited_countries_sarca',
            new_name='visited_countries_saarca',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_visited_visa_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Место выдачи визы '),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_visited_visa_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип визы '),
        ),
    ]
