# Generated by Django 3.2.9 on 2022-12-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20221219_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='is_visited_address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_visited_cities',
            field=models.CharField(blank=True, max_length=256, verbose_name='Посещенные города '),
        ),
    ]
