# Generated by Django 4.1.4 on 2022-12-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_question_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='types',
        ),
    ]
