# Generated by Django 4.1.4 on 2022-12-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_subquestion_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='is_refused_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата отказа '),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_visited_visa_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата визы '),
        ),
    ]
