# Generated by Django 4.1.4 on 2022-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_questionnaire_is_refused_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subquestion',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='title_uz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Savolni tagi'),
        ),
    ]
