# Generated by Django 4.1.4 on 2022-12-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_title_subquestion_title_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title_ru',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subquestion',
            old_name='title_ru',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='title_uz',
        ),
    ]
