# Generated by Django 4.1.4 on 2023-01-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_questionnaire_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата регистрации: '),
        ),
    ]
