# Generated by Django 4.1.4 on 2023-01-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_questionnaire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации: '),
        ),
    ]
